name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "olostep-webscrapper" #Must be unique in Heroku
          heroku_email: "ktarafder01@gmail.com"
          team: "olostep-webscrapper"
          usedocker: true